//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCarpet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pcarpetEntities : DbContext
    {
        public pcarpetEntities()
            : base("name=pcarpetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<master> master { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<slave> slave { get; set; }
        public virtual DbSet<slot> slot { get; set; }
        public virtual DbSet<stop> stop { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
