//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCarpet
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.car = new HashSet<car>();
            this.payment = new HashSet<payment>();
            this.report = new HashSet<report>();
            this.slot = new HashSet<slot>();
            this.book = new HashSet<book>();
        }

        public user(string username, string password, int type, string name, string surname, string address, int? cap, string handiccaped, string phone, string email)
        {
            this.username = username;
            this.password = password;
            this.type = type;
            this.name = name;
            this.surname = surname;
            this.address = address;
            this.cap = cap;
            this.handiccaped = handiccaped;
            this.phone = phone;
            this.email = email;
        }

        public string username { get; set; }
        public string password { get; set; }
        public int type { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public Nullable<int> cap { get; set; }
        public string handiccaped { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<car> car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<slot> slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> book { get; set; }
    }
}
