//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCarpet
{
    using System;
    using System.Collections.Generic;
    
    public partial class stop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stop()
        {
            this.payment = new HashSet<payment>();
        }
    
        public int Id { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime finish { get; set; }
        public int carId { get; set; }
        public int SlotId { get; set; }
    
        public virtual car car { get; set; }
        public virtual slot Slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
    }
}
